### PR TITLE
1043 go functions crash

### LINKED ISSUE #1043: App crashes with no error screen when selecting functions tab in POA
## Expected Behavior

The table loads cleanly

## Actual Behavior

The page is white. There are errors in the console.log. No error boundary is displayed

Errors are as follows:
```
Fabric Server Detected
main.b37f35aa.js:14 TypeError: Cannot read property '1' of null
    at https://edge.deciphernow.com/static/js/6.ae98992a.chunk.js:1:168
    at Array.map (<anonymous>)
    at a (https://edge.deciphernow.com/static/js/6.ae98992a.chunk.js:1:116)
    at https://edge.deciphernow.com/static/js/6.ae98992a.chunk.js:1:2615
    at https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:54457
    at https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:53884
    at https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:54587
    at https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:53884
    at https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:54555
    at https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:53884
    at Function.o [as mapToProps] (https://edge.deciphernow.com/static/js/6.ae98992a.chunk.js:1:3922)
    at r (https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:81158)
    at c (https://edge.deciphernow.com/static/js/main.b37f35aa.js:22:43103)
    at s (https://edge.deciphernow.com/static/js/main.b37f35aa.js:22:43221)
    at https://edge.deciphernow.com/static/js/main.b37f35aa.js:22:43374
    at Object.run (https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:74070)
    at l.onStateChange (https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:76924)
    at Object.notify (https://edge.deciphernow.com/static/js/main.b37f35aa.js:22:34112)
    at t.notifyNestedSubs (https://edge.deciphernow.com/static/js/main.b37f35aa.js:22:34640)
    at l.onStateChange (https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:77066)
    at Object.notify (https://edge.deciphernow.com/static/js/main.b37f35aa.js:22:34112)
    at t.notifyNestedSubs (https://edge.deciphernow.com/static/js/main.b37f35aa.js:22:34640)
    at l.onStateChange (https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:77066)
    at Object.notify (https://edge.deciphernow.com/static/js/main.b37f35aa.js:22:34112)
    at t.notifyNestedSubs (https://edge.deciphernow.com/static/js/main.b37f35aa.js:22:34640)
    at l.onStateChange (https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:77066)
    at l (https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:79606)
    at https://edge.deciphernow.com/static/js/main.b37f35aa.js:22:51204
    at https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:17426
    at dispatch (https://edge.deciphernow.com/static/js/main.b37f35aa.js:22:41584)
    at e.dispatch (https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:17911)
    at l (https://edge.deciphernow.com/static/js/main.b37f35aa.js:34:201203)
    at Object.c.(anonymous function) [as appendToMetrics] (https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:42445)
    at o (https://edge.deciphernow.com/static/js/main.b37f35aa.js:46:10249)
    at Object.n [as fetchMetricsSuccess] (https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:116908)
    at https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:17488
    at dispatch (https://edge.deciphernow.com/static/js/main.b37f35aa.js:22:41584)
    at e.dispatch (https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:17911)
    at https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:117285
    at new Promise (<anonymous>)
    at l (https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:117219)
    at Object.c.(anonymous function) [as fetchMetricsSuccess] (https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:42610)
    at https://edge.deciphernow.com/static/js/main.b37f35aa.js:46:9969
    at <anonymous>
c @ main.b37f35aa.js:14
main.b37f35aa.js:6 Fetching Metrics failed TypeError: Cannot read property '1' of null
    at https://edge.deciphernow.com/static/js/6.ae98992a.chunk.js:1:168
    at Array.map (<anonymous>)
    at a (https://edge.deciphernow.com/static/js/6.ae98992a.chunk.js:1:116)
    at https://edge.deciphernow.com/static/js/6.ae98992a.chunk.js:1:2615
    at https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:54457
    at https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:53884
    at https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:54587
    at https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:53884
    at https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:54555
    at https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:53884
    at Function.o [as mapToProps] (https://edge.deciphernow.com/static/js/6.ae98992a.chunk.js:1:3922)
    at r (https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:81158)
    at c (https://edge.deciphernow.com/static/js/main.b37f35aa.js:22:43103)
    at s (https://edge.deciphernow.com/static/js/main.b37f35aa.js:22:43221)
    at https://edge.deciphernow.com/static/js/main.b37f35aa.js:22:43374
    at Object.run (https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:74070)
    at l.onStateChange (https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:76924)
    at Object.notify (https://edge.deciphernow.com/static/js/main.b37f35aa.js:22:34112)
    at t.notifyNestedSubs (https://edge.deciphernow.com/static/js/main.b37f35aa.js:22:34640)
    at l.onStateChange (https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:77066)
    at Object.notify (https://edge.deciphernow.com/static/js/main.b37f35aa.js:22:34112)
    at t.notifyNestedSubs (https://edge.deciphernow.com/static/js/main.b37f35aa.js:22:34640)
    at l.onStateChange (https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:77066)
    at Object.notify (https://edge.deciphernow.com/static/js/main.b37f35aa.js:22:34112)
    at t.notifyNestedSubs (https://edge.deciphernow.com/static/js/main.b37f35aa.js:22:34640)
    at l.onStateChange (https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:77066)
    at l (https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:79606)
    at https://edge.deciphernow.com/static/js/main.b37f35aa.js:22:51204
    at https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:17426
    at dispatch (https://edge.deciphernow.com/static/js/main.b37f35aa.js:22:41584)
    at e.dispatch (https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:17911)
    at l (https://edge.deciphernow.com/static/js/main.b37f35aa.js:34:201203)
    at Object.c.(anonymous function) [as appendToMetrics] (https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:42445)
    at o (https://edge.deciphernow.com/static/js/main.b37f35aa.js:46:10249)
    at Object.n [as fetchMetricsSuccess] (https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:116908)
    at https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:17488
    at dispatch (https://edge.deciphernow.com/static/js/main.b37f35aa.js:22:41584)
    at e.dispatch (https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:17911)
    at https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:117285
    at new Promise (<anonymous>)
    at l (https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:117219)
    at Object.c.(anonymous function) [as fetchMetricsSuccess] (https://edge.deciphernow.com/static/js/main.b37f35aa.js:6:42610)
    at https://edge.deciphernow.com/static/js/main.b37f35aa.js:46:9969
    at <anonymous>
```

## Steps to Reproduce the Problem

  1. Navigate to https://edge.deciphernow.com/#/Up2·Service/1.0/d74a7445dda6b94564509977120b185e/functions
  
## Supporting Images or Videos

image

## Specifications

  - Version: 1.0.0
  - Platform: Mac OS High Sierra
  - Subsystem: Chrome 62

### PR DESCRIPTION
**Pull request by spmcbride1201**
Resolves #1043 

## Proposed Changes

  - The "functions" and "Routes" keys must now match the first characters of the key to prevent errors from occuring if the keys contain the work "function" or "route" anywhere else in the key
  - Added supporting unit tests and fixes test regressions causes by the changes to the mock data needed to recreate the issue.
  
## How to Test

  - Look at the mock data and notice that it now contains a series of keys starting with `route/functionalroles/GET/`. Previously, this was causing the key to match as a function
  - Run `npm test` to ensure that the unit tests are running cleanly
  - Run `npm start` and `npm mock-sds` and navigate to the functions tab of a Go microservice to ensure that the app does not crash.
  - If desired, change the import in `sds.js` from `metricsWithFunctions` to `metricsWithoutFunctions` and restart mock-sds to ensure the app handles both scenarios.

### CODE REVIEW

**Comment by spmcbride1201** [comment]
Looking back at code climate, I do actually think it makes sense to turn those two selectors into a general purpose selector generator to DRY things up. I'll do that tomorrow.

File: src/utils/selectors.js [hunk 1]
```diff
@@ -123,15 +123,31 @@ export const generateHeaderTabs = createSelector(
...
  */
-export const getRoutesMetrics = createSelector([getMetrics], metrics => {
-  return _.pick(
-    metrics,
-    Object.keys(metrics).filter(key => key.indexOf("route") !== -1)
+export function metricsKeySelectorGenerator(keyQuery, isPrefix = true) {
+  const filterFunc = isPrefix
+    ? key => key.substr(0, keyQuery.length) === keyQuery
+    : key => key.indexOf(keyQuery) !== -1;
+  return createSelector([getMetrics], metrics =>
```
Comment (kaitmore) [inline src/utils/selectors.js]: Nice!!
