### PR TITLE
745 fix: routes table line item error percent color and NaN

### LINKED ISSUE #745: Routes Table Line Item Error % Issues
1. The error % is resolving to NaN in some cases
2. The error % is using a yellow color that is very hard to make out on a white background.

Note: this was seen in a JVM microservice, but it likely is also occurring with other runtimes.

image

### PR DESCRIPTION
**Pull request by karinakeen**
This PR resolves #745 

Fix: 
-The error % is resolving to NaN in some cases -> all NaN edge cases eliminated
-The error % is using a yellow color that is very hard to make out on a white background. -> changed to dark dark yellow

The existing error color function will be enhanced in issue #807

### CODE REVIEW

**Comment by karinakeen** [comment]
Updated code to reflect the latest error percent handling merges in master

File: src/components/Main/scenes/Instance/scenes/go/scenes/Summary.js [hunk 1]
```diff
@@ -76,14 +76,18 @@ class SummaryGrid extends Component {
     const allRequests = getLatestAttribute(metrics, "all/requests");
     const allErrors = getLatestAttribute(metrics, "all/errors.count");
     const errorPercent =
-      allRequests > 0
+      allRequests && allErrors
```
Comment (spmcbride1201) [inline src/components/Main/scenes/Instance/scenes/go/scenes/Summary.js]: Can you refactor to use `calculateErrorPercent` and `formatAsDecimalString`?
