### PR TITLE
Fix: Sort Select Dropdown flickering on route change

### LINKED ISSUE #853: Sort Select flickers in and out when clicking different summary cards on Fabric Dashboard

### PR DESCRIPTION
**Pull request by kaitmore**
Resolves #853  

I moved the `statusView` state from FabricGrid to the top level router in `generateStatusRoutes.js`. `statusView` will default to false for the root route.

### CODE REVIEW

File: src/components/Main/scenes/Fabric/FabricGrid.js [hunk 1]
```diff
@@ -185,7 +180,7 @@ class FabricGrid extends Component {
   };
 
   render() {
-    const { services = [] } = this.props;
+    const { services = [], statusView = false } = this.props;
```
Comment (tilleryd) [inline src/components/Main/scenes/Fabric/FabricGrid.js]: I think the default value of statusView should be set using React's `defaultProp` pattern.

```
  ...
  static defaultProps = {
    statusView: false
  };
  ...
  render() {
    const { services = [] } = this.props;
    ...
  }
```

**Comment by kaitmore** [comment]
@tilleryd Implemented defaultProps in FabricGrid
