### PR TITLE
WIP: #803 IE: Explorer layout fix

### LINKED ISSUE #803: IE: Explorer layout
Issues with flexbox in IE:

screen shot 2017-11-01 at 1 32 55 pm

### PR DESCRIPTION
**Pull request by 7ruth**
Resolves #803

### CODE REVIEW

File: src/components/library/IEFlexWrapper.js [hunk 1]
```diff
@@ -0,0 +1,11 @@
+// This wrapper helps IE recognize min-height of a flex container and apply it to its flex children, refer to the link below for more details on this IE defect
+// https://github.com/philipwalton/flexbugs#3-min-height-on-a-flex-container-wont-apply-to-its-flex-items
+
+import styled from "styled-components";
+
+const IEFlexWrapper = styled.div`
```
Comment (shanberg) [inline src/components/library/IEFlexWrapper.js]: What happens if you apply these styles to the `#root` element via injectGlobal instead of adding an additional component?

Comment (kaitmore) [reply src/components/library/IEFlexWrapper.js]: Good idea, I'll try it out.

Comment (spmcbride1201) [reply src/components/library/IEFlexWrapper.js]: Probably a good idea to prepend WIP: to the title of PRs that you're actively working on just in case someone is tempted to hit the update button on you.

Comment (7ruth) [reply src/components/library/IEFlexWrapper.js]: incorporated @shanberg feedback, works like a charm
