### PR TITLE
1109 outline on keyboard not click

### LINKED ISSUE #1109: Make sure divs and buttons only get outlined on tab and not onclick
## Expected Behavior

- divs and buttons should only get outline on tab over

## Actual Behavior

- divs and buttons get outlined on click

## Steps to Reproduce the Problem

- Navigate to any of the places listed in Observed In section and click on the mentioned element

## Specifications

  - Version: 1.0.1
  - Platform: fabric

## Observed in 

All drawers: Routes, Functions, Threads (JVM/GO)
Service Instances view (table rows and links within)
Clear Cache modal in settings view
TableToolbar gm-select dropdowns

### PR DESCRIPTION
**Pull request by 7ruth**
Resolves #1109 

## Proposed Changes

  -Changing several onClick events and some css properties to make sure table rows are only outlined on keyboard actions and not on mouse clicks.
  -Changes took place in several places:
    JVM: routes, threads, explorer
    GO: routes, functions, explorer
    services instance view
  
## How to Test

  - Navigate to places listed above and use mouse and tab actions to compare results.
  -Goal: tabs highlight selections... clicks do not... while having same behavior in all supported browsers and passing out tests.

Tested in IE11, chrome, FF52 and latest Safari (note: In Safari, to make this work in instance table view... need to go to Safari preferences> advanced and check "press tab to highlight...")

### CODE REVIEW

File: src/components/Main/components/TableRow.js [hunk 1]
```diff
@@ -12,6 +12,8 @@ import {
   TABLE_HOVER
 } from "style/styleVariables";
 
+// outline: ${props => (true ? "0" : "-webkit-focus-ring-color auto 5px;")};
```
Comment (kaitmore) [inline src/components/Main/components/TableRow.js]: forgot this guy

File: src/components/Main/scenes/InstanceView/scenes/GoInstanceView/scenes/Functions/components/FunctionsTable/components/LineItem.js [hunk 2]
```diff
@@ -38,15 +38,18 @@ export default class FunctionsTableLineItem extends Component {
     isOpen: false
   };
 
-  toggleDrawer = () => {
+  toggleDrawer = node => {
+    if (node) {
+      node.blur();
```
Comment (kaitmore) [inline src/components/Main/scenes/InstanceView/scenes/GoInstanceView/scenes/Functions/components/FunctionsTable/components/LineItem.js]: Great use of blur()! Maybe you could add some comments to explain what's going on?

File: src/components/Main/scenes/InstanceView/scenes/GoInstanceView/scenes/Functions/components/FunctionsTable/components/LineItem.test.js [hunk 3]
```diff
@@ -56,18 +58,18 @@ describe("Go Instance Routes View: <FunctionsTableLineItem/>", () => {
     wrapper = shallow(FunctionsTableLineItemWithProps);
 
     const row = wrapper.find(TableRow);
-    row.simulate("click");
+    row.simulate("click", mockedEvent);
```
Comment (kaitmore) [inline src/components/Main/scenes/InstanceView/scenes/GoInstanceView/scenes/Functions/components/FunctionsTable/components/LineItem.test.js]: Just curious, why do you need to provide the mock event?

**Comment by kaitmore** [comment]
I really like your approach! It seems pretty optimal to me. Nice job persisting until you found the best solution.

The one place I was still noticing an outline on click is on Fabric main list view.

File: src/components/Main/scenes/InstanceView/scenes/GoInstanceView/scenes/Functions/components/FunctionsTable/components/LineItem.test.js (hunk 3 above)
Comment (7ruth) [reply src/components/Main/scenes/InstanceView/scenes/GoInstanceView/scenes/Functions/components/FunctionsTable/components/LineItem.test.js]: So I added this piece to the code,  
``` onClick={evt => this.toggleDrawer(evt.target.parentNode)} ```
I need to test it... peculiarity of .simulate (from documentation): 
``` Even though the name would imply this simulates an actual event, .simulate() will in fact target the component's prop based on the event you give it. For example, .simulate('click') will actually get the onClick prop and call it. ```

You need to pass a mock event object to .simulate, otherwise tests errors out on "can't get .target of undefined" (evt.target).

Comment (kaitmore) [reply src/components/Main/scenes/InstanceView/scenes/GoInstanceView/scenes/Functions/components/FunctionsTable/components/LineItem.test.js]: cool 👍🏼

**Comment by 7ruth** [comment]
Resolves #1101
