### PR TITLE
1064 browserslist

### LINKED ISSUE #1064: Implement our Browser Support Matrix using babel-preset-env
## Steps to Reproduce the Problem

  1.
  1.
  1.
  
## Specifications

  - Version:
  - Platform:
  - Subsystem:

### PR DESCRIPTION
**Pull request by spmcbride1201**
Resolves #1064 

## Proposed Changes

  - Pull `babel-preset-react-app` logic into a local file and modify to contain our plugins and presets
  - Add browserslist logic with out browser support matrix, and configure babel env and PostCSS autoprefixer to use the file. Unfontunately, babel env cannot use the browserslist value in `package.json` until babel 7.x is released, so I've had to implement the list separately as a node module.
  
## How to Test

  - Run the app locally and test in our supported browsers via BrowserStack
  - Run Storybook
  - Run `npm test`
  - Run `npm run build` and confirm that the build process completes.

### CODE REVIEW

File: config/browserslist.js [hunk 1]
```diff
@@ -0,0 +1,12 @@
...
+  "last 2 ChromeAndroid versions",
+  "last 2 Safari versions",
+  "last 2 iOS versions",
+  "last 2 Firefox versions",
+  "IE 11",
+  "last 2 Edge versions",
+  "Firefox ESR"
+];
+
+module.exports = { browserlist };
```
Comment (kaitmore) [inline config/browserslist.js]: You are exporting this as `browserlist` and everywhere else you have `browserslist`
