### PR TITLE
fixed: text overflow within cards name is now trancated and any card …

### LINKED ISSUE #674: Long card titles overflow
When a card title is too long it needs to be truncated

screen shot 2017-10-24 at 10 11 44 am

### PR DESCRIPTION
**Pull request by 7ruth**
…that does have an overflow name now has a title hover tooltip with the full non-truncated name in it

Resolves #674

### CODE REVIEW

File: src/components/Main/scenes/Fabric/components/FabricMainView/scene/Card/components/GMServiceCardCollection/components/GMServiceCard/components/Title.js [hunk 1]
```diff
@@ -4,7 +4,9 @@ import {
   FONT_STACK_DATA
 } from "../../../../../../../../../../../../../style/styleVariables";
 
-const Title = styled.div`
+const Title = styled.div.attrs({
+  title: props => props.title || null
+})`
```
Comment (kaitmore) [inline src/components/Main/scenes/Fabric/components/FabricMainView/scene/Card/components/GMServiceCardCollection/components/GMServiceCard/components/Title.js]: Since title is a standard attribute, styled-components will actually pass it down to the DOM element for you. So you can probably get rid of this.

File: src/components/Main/scenes/Fabric/components/FabricMainView/scene/Card/components/GMServiceCardCollection/components/GMServiceCard/index.js [hunk 2]
```diff
@@ -39,6 +39,10 @@ export default function GMServiceCard({
     cardBorderBottomColor,
     iconUrl;
   const baseColor = mapStatusToColor(status).string();
+  const maxNameLen = 40;
```
Comment (kaitmore) [inline src/components/Main/scenes/Fabric/components/FabricMainView/scene/Card/components/GMServiceCardCollection/components/GMServiceCard/index.js]: The maxNameLen might need to be a little shorter. I see a couple cards with titles that overlap the version:

screen shot 2017-10-25 at 4 40 48 pm

Comment (shanberg) [reply src/components/Main/scenes/Fabric/components/FabricMainView/scene/Card/components/GMServiceCardCollection/components/GMServiceCard/index.js]: The max length before overflow will change at the latest master because the title leading has been reduced. I was able to get up to 52 without any clipping when I tested locally.

File: src/components/Main/scenes/Fabric/components/FabricMainView/scene/Card/components/GMServiceCardCollection/components/GMServiceCard/index.js [hunk 3]
```diff
@@ -39,6 +39,10 @@ export default function GMServiceCard({
...
+  const titleName =
+    name.length > maxNameLen ? `${name.substr(0, maxNameLen)}...` : name;
```
Comment (shanberg) [inline src/components/Main/scenes/Fabric/components/FabricMainView/scene/Card/components/GMServiceCardCollection/components/GMServiceCard/index.js]: Can we trim the whitespace at the end of the title, in case it truncates at a space character?

File: src/components/Main/scenes/Fabric/components/FabricMainView/scene/Card/components/GMServiceCardCollection/components/GMServiceCard/index.js (hunk 2 above)
Comment (7ruth) [reply src/components/Main/scenes/Fabric/components/FabricMainView/scene/Card/components/GMServiceCardCollection/components/GMServiceCard/index.js]: Setting it to 52 then.

Comment (kaitmore) [reply src/components/Main/scenes/Fabric/components/FabricMainView/scene/Card/components/GMServiceCardCollection/components/GMServiceCard/index.js]: 👍🏼
