### PR TITLE
1194 styled components unit tests

### LINKED ISSUE #1194: Add snapshots for all styled-components
## Steps to Reproduce the Problem

  1.
  1.
  1.
  
## Specifications

  - Version:
  - Platform:
  - Subsystem:

### PR DESCRIPTION
**Pull request by spmcbride1201**
Resolves #1194 

## Proposed Changes

  - Implement snapshots and jest-styled-components tests for all styled-components

## How to Test

  - `npm test`

### CODE REVIEW

File: src/components/ConfirmationModal/ConfirmationModal.js [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+
+ConfirmationModal.propTypes = {
+  isOpen: PropTypes.bool.isRequired,
+  onCancel: PropTypes.func.isRequired,
+  onConfirm: PropTypes.func.isRequired,
+  question: PropTypes.string.isRequired,
+  secondary: PropTypes.string.isRequired
+};
+
+export default ConfirmationModal;
```
Comment (7ruth) [inline src/components/ConfirmationModal/ConfirmationModal.js]: There is a warning that pops-up due to the use of the modal. https://github.com/reactjs/react-modal/issues/133
I already have a ticket dealing with accessibility issues of the modal on my plate and I can deal with it within that issue rather than making adjustments within the scope of this issue.
