### PR TITLE
fix: if a status category doesnt receive microservices its section wi…

### LINKED ISSUE #723: Fabric Page: Empty groupings should not be displayed
On the Fabric page in a Cards view, with Group: Status and Sort: Name, if the Down and Warning groups are empty, I think we should hide them from the view.

There are probably other things we should do in this case, but I can't think of them at the moment.

### PR DESCRIPTION
**Pull request by 7ruth**
…ll no longer be visible in the list view

Resolves #723 

## Proposed Changes

  -Adding a check to see if microservices are present under a heading key, if not, that section should not be rendered in the list view
  
## How to Test

  - /FabricMainView/scene/ServicesListView/ServicesListView.js
  - around line 48, add something similar to dataGroupedByHeader['down']='';
  - Navigate to list view after, no empty section should be visible.

### CODE REVIEW

File: src/components/Main/scenes/FabricView/components/FabricGrid/components/FabricMainView/scene/ServicesListView/ServicesListView.js [hunk 1]
```diff
@@ -31,23 +31,29 @@ function ListView({
...
-    } else if (!statusSort && groupByAttribute === "Status") {
+    // If we are sorting by status, use microServiceStatuses as the headers
+    // as they need to be in the order "Down, Warning, Stable"
+    if (groupByAttribute === "Status") {
       headers = microserviceStatuses.map(item => item.toLowerCase());
     } else {
       headers = headerTitles;
     }
 
+    let verifiedHeaders = [];
```
Comment (kaitmore) [inline src/components/Main/scenes/FabricView/components/FabricGrid/components/FabricMainView/scene/ServicesListView/ServicesListView.js]: You can delete this line and initiate the variable on line 46 
`let verifiedHeaders = headers.filter...`
