### PR TITLE
Fix: Redirect on invalid instance

### LINKED ISSUE #879: Improve User Experience for an Instance of a Valid Microservice not existing
If a route has a microservice and version that matches but an invalid Instance ID, the app renders the Instance Dashboard (likely for the default runtime), starts polling without knowing a valid endpoint, and then errors out.

image

Desired Behavior:

* After the dashboard mounts, wait for the response from /services to learn if this microservice and version exist or not.
* If the microservice name and version and valid, check to see if the instance ID matches a value associated with the microservice name and version.
* If the instance ID matches, begin polling
* If the instance ID does not match, redirect back to the Fabric Dashboard and present a notification that the "489375340fsd87gf9-384qf4 is not a known instance of Service Name version 2.0";

### PR DESCRIPTION
**Pull request by kaitmore**
Resolves #879

### CODE REVIEW

File: src/components/Main/scenes/Fabric/FabricGrid.js [hunk 1]
```diff
@@ -41,18 +41,10 @@ class FabricGrid extends Component {
...
-      // Reset location state
-      history.replace({
-        state: ""
-      });
-    } else if (state && !state.metered) {
-      notification(`${state.serviceName} does not have metrics to display`, {
+    // State added by fabric router
+    // Display message if one is found on state
+    if (state && state.message) {
+      notification(state.message, {
```
Comment (spmcbride1201) [inline src/components/Main/scenes/Fabric/FabricGrid.js]: Can you please refactor to use the reportError utility function?

File: src/components/Main/scenes/Fabric/index.js [hunk 2]
```diff
@@ -53,15 +53,31 @@ function FabricRouter({ services }) {
           const metered = service && service.metered;
           // Lookup the runtime of the microservice named serviceName
           const runtime =
-            services && serviceName && services[`${serviceName}|${version}`]
-              ? services[`${serviceName}|${version}`].runtime
-              : "";
-          // runtime informs the runtime-agnostic InstanceRouter which runtime router to render
-          // baseURL is prefixed to route paths and link to attributes when running with Fabric Server
+            services && serviceName && service ? service.runtime : "";
```
Comment (spmcbride1201) [inline src/components/Main/scenes/Fabric/index.js]: I'm thinking this could be a bit easier to understand if the variables are named to make it a bit more clear that they're booleans:
- userIsAuthorized
- serviceIsMetered
- instanceIsValid

**Comment by spmcbride1201** [comment]
Looking back at the issue, I think I mistyped. The behavior for this scenario should be to redirect to the service dashboard (showing the list of instances).

**Comment by kaitmore** [comment]
@spmcbride1201 @karinakeen 

- [x] Added version # to error message
- [x] An invalid instance now redirects to the service dashboard instead of Fabric Grid
- [x] Refactored notifications to use reportError utility function
