### PR TITLE
fix: routes table view - error NaN percentage

### LINKED ISSUE #480: Dashboard view: Routes table view- Error % - NaN%
Dashboard view: Routes table view- Error % displayed as NaN%

NaN% 

screen shot 2017-10-05 at 2 56 11 pm

screen shot 2017-10-05 at 2 55 57 pm

### PR DESCRIPTION
**Pull request by karinakeen**
Resolves #480

### CODE REVIEW

File: src/components/instance/go/FunctionsTableLineItem.js [hunk 1]
```diff
@@ -9,7 +9,7 @@ import {
 import GMLineChart from "../../library/GMLineChart";
 
 /**
- * A row of data in the Go FunctionsTable 
+ * A row of data in the Go FunctionsTable
```
Comment (spmcbride1201) [inline src/components/instance/go/FunctionsTableLineItem.js]: Out of curiosity, was this you or Prettier?

File: src/components/instance/go/FunctionsTableLineItem.js [hunk 2]
```diff
@@ -34,10 +34,15 @@ export default class FunctionsTableLineItem extends Component {
   };
 
   render() {
-    const errorPercent =
-      (1 -
-        (this.props.requests - this.props.errorsCount) / this.props.requests) *
-      100;
+    // initialize errorPercent as zero and calculate errorPercent if number of requests is not zero
+    let errorPercent = 0;
```
Comment (spmcbride1201) [inline src/components/instance/go/FunctionsTableLineItem.js]: Looks great!

File: src/components/instance/go/FunctionsTableLineItem.js (hunk 1 above)
Comment (karinakeen) [reply src/components/instance/go/FunctionsTableLineItem.js]: Prettier.
